spring:
  application:
    name: home-archive
  
  profiles:
    active: dev
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
        # Enable statistics for performance monitoring
        generate_statistics: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 1000
        # Register query performance interceptor
        session_factory:
          statement_inspector: com.homearchive.config.QueryPerformanceInterceptor
    # Open EntityManager in view to prevent lazy loading issues
    open-in-view: false
  
  # Database connection pool monitoring
  datasource:
    hikari:
      # Connection pool settings for monitoring
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
      # Enable detailed metrics
      register-mbeans: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  
  actuator:
    endpoints:
      web:
        exposure:
          # Add database and performance monitoring endpoints
          include: health,info,metrics,hikaricp,liquibase,flyway,database-performance
    endpoint:
      health:
        show-details: when-authorized
    metrics:
      export:
        simple:
          enabled: true

# Enhanced logging for database performance monitoring
logging:
  level:
    com.homearchive: INFO
    org.springframework.security: DEBUG
    # Database query logging
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.stat: DEBUG
    # Connection pool logging
    com.zaxxer.hikari: DEBUG
    # Query performance logging
    org.springframework.jdbc.core: DEBUG
    # Access logging
    ACCESS: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  loggers:
    ACCESS:
      level: INFO
      additivity: false
      appenders:
        - name: ACCESS_FILE
          type: RollingFileAppender
          fileName: logs/access.log
          filePattern: logs/access.%d{yyyy-MM-dd}.log
          maxFileSize: 10MB
          maxHistory: 30

server:
  port: 8080
  servlet:
    context-path: /api

# Performance monitoring configuration
management:
  metrics:
    enable:
      hikaricp: true
      jdbc: true
      jvm: true
      system: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.50, 0.95, 0.99
      sla:
        http.server.requests: 100ms, 200ms, 500ms

# Application-specific configuration
app:
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:8080,https://localhost:3000"
  security:
    headers:
      enabled: true
  logging:
    request-response:
      enabled: true
      include-payload: false
      max-payload-length: 1000